conf/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photos.urls')),
]

photos/urls.py
from django.urls import path

from . import views

app_name = 'photos'

urlpatterns = [
    # This is the route for the home page
    path('', views.HomeView.as_view(), name='home'),

    # This route includes value capturing to grab the contest id as the pk variable
    # Example: localhost:8000/5/ <-- The # 5 is saved to a variable pk that we
    # can use in the view.
    path('<int:pk>/', views.ContestDetailView.as_view(), name='detail'),

    # This route includes value capturing to grab the contest id as the pk variable
    path('<int:pk>/results/', views.ContestResultsView.as_view(), name='results'),

    # This route includes value capturing to grab the contest id as the pk variable
    path('<int:pk>/vote/', views.ContestVoteView.as_view(), name='vote'),
]

photos/models.py
from django.db import models


class Photo(models.Model):
    contest = models.ForeignKey('photos.Contest', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    picture = models.URLField()
    description = models.TextField(null=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Contest(models.Model):
    title = models.CharField(max_length=255)
    date_published = models.DateField()

    def __str__(self):
        return self.title

photos/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, View
from django.utils import timezone

from .models import Photo, Contest


class HomeView(TemplateView):
    template_name = 'photos/home.html'

    def get_context_data(self, **kwargs):
        """
        Return the last five published contests (not including those set to be
        published in the future).
        """
        contests = Contest.objects.filter(
            date_published__lte=timezone.now()
        ).order_by('-date_published')[:5]

        context = {
            'latest_contests': contests
        }

        return context


class ContestDetailView(TemplateView):
    template_name = 'photos/detail.html'

    def get_context_data(self, **kwargs):
        # The contest primary key is included on the url: locahost:8000/5/
        # We use value capturing in our urls.py to get the # 5 and save it to pk
        # The pk variable is in the dictionary self.kwargs, and we can use .get() on
        # the self.kwargs dict.
        contest_pk = self.kwargs.get('pk')

        # Now that we have the primary key for the contest, use the ORM to get the
        # object from the database
        contest = Contest.objects.get(pk=contest_pk)

        # Create a context dictionary that will be sent to our template
        context = {
            'contest': contest
        }

        # Our get_context_data() function always expects us to return a context dict
        return context


class ContestResultsView(TemplateView):
    template_name = 'photos/results.html'

    def get_context_data(self, **kwargs):
        # The contest primary key is included on the url: locahost:8000/5/results/
        # We use value capturing in our urls.py to get the # 5 and save it to pk
        # The pk variable is in the dictionary self.kwargs, and we can use .get() on
        # the self.kwargs dict.
        contest_pk = self.kwargs.get('pk')

        # Now that we have the primary key for the contest, use the ORM to get the
        # object from the database
        contest = Contest.objects.get(pk=contest_pk)

        # Create a context dictionary that will be sent to our template
        context = {
            'contest': contest
        }

        # Our get_context_data() function always expects us to return a context dict
        return context


# This view will not be a template view since we won't actually show a screen.
# Once a user submits to this screen we will redirect.
class ContestVoteView(View):

    # We are going to receive a POST request with this view, so we're going to create a method called post.
    def post(self, request, **kwargs):
        # The contest primary key is included on the url: locahost:8000/5/vote/
        # We use value capturing in our urls.py to get the # 5 and save it to pk
        # The pk variable is in the dictionary self.kwargs, and we can use .get() on
        # the self.kwargs dict.
        contest_pk = self.kwargs.get('pk')

        # Now that we have the primary key for the contest, use the ORM to get the
        # object from the database
        contest = Contest.objects.get(pk=contest_pk)

        # The user selected a picture that they wanted to vote for in the contest.
        # They selected one of the radio buttons: <input name="photo" value="2" .../>
        # When they submitted the form, the name of the input got sent to the server with the value in the input.
        # We can use the input name get the value from the POST dictionary.
        photo_voted_for_id = self.request.POST.get('photo')

        # Now we want to take our contest and lookup the photo object that the user selected
        selected_photo = contest.photo_set.get(pk=photo_voted_for_id)

        selected_photo.votes += 1
        selected_photo.save()

        # Now get the URL for our results screen using the route name from urls.py
        results_url = reverse('photos:results', args=(contest.pk,))

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(results_url)

photos/templates/photos/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Hipster Puppies</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/styles.css">
</head>

<body>

    <div class="container">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <script type="text/javascript" src="/static/js/main.js"></script>
</body>

</html>

photos/templates/photos/detail.html
{% extends 'photos/base.html' %}


{% block content %}

    <h1>{{ contest.title }}</h1>


    {# Our form action needs to point to our vote route, we use the url template tag again #}
    <form action="{% url 'photos:vote' contest.id %}" method="post" class="row">
        {% csrf_token %} {# The CSRF token is a security measure #}

        {% for photo in contest.photo_set.all %}
            <div class="col-md-4">
                <div class="card">
                    <label for="photo{{ forloop.counter }}">
                        <img class="card-img-top" src="{{ photo.picture }}" />
                    </label>

                    <div class="card-body">
                        <h5 class="card-title">{{ photo.title }}</h5>

                        Select: <input type="radio" name="photo" id="photo{{ forloop.counter }}" value="{{ photo.id }}" />
                    </div>

                </div>
            </div>
        {% endfor %}

        <input type="submit" class="btn btn-primary" value="Vote" />
    </form>


{% endblock %}

photos/templates/photos/home.html
{% extends 'photos/base.html' %}

{% block content %}

    <div class="jumbotron">
        <h1>Welcome to Hipster Puppies!</h1>
        <h2>We run Hipster Puppy Contests where you can vote for the most hipster puppies of the web.</h2>
    </div>

    {% if latest_contests %}
        <ul class="list-group">
            {# Loop over the latest_contests list and get each contest #}
            {% for contest in latest_contests %}
                {# We can build a url with the name of our path using the url template tag #}
                <li class="list-group-item"><a href="{% url 'photos:detail' contest.id %}">{{ contest.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No hipster puppy contests are available.</p>
    {% endif %}

{% endblock %}

photos/templates/photos/results.html
{% extends 'photos/base.html' %}


{% block content %}

    <div class="jumbotron col-md-12">
        <h1>{{ contest.title }}</h1>
    </div>

    <div class="col-md-8">
        <ul class="list-group">
            {% for photo in contest.photo_set.all %}
                <li class="list-group-item">{{ photo.title }} -- {{ photo.votes }} vote{{ photo.votes|pluralize }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="col-md-4">
        <a href="{% url 'photos:detail' contest.id %}">Vote again?</a>
    </div>
{% endblock %}